SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE DATABASE IF NOT EXISTS `rox` DEFAULT CHARACTER SET `utf8`;
USE `rox`;
CREATE TABLE IF NOT EXISTS `rox`.`special_offer_product` (
    `SpecialOfferID` INT NOT NULL,
    `ProductID` INT NOT NULL,
    `rowguid` VARCHAR(255) NOT NULL,
    `ModifiedDate` DATETIME NOT NULL,
    PRIMARY KEY (`SpecialOfferID`,`ProductID`),
    INDEX `ProductID_idx` (`ProductID`),
    FOREIGN KEY (`ProductID`) REFERENCES `rox`.`product` (`ProductID`)
)

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;